# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='user', max_length=30),
            preserve_default=False,
        ),
    ]
